run_conda: &run_conda
    docker:
        - image: circleci/python
          environment:
              ARCCSSIVE_DB: postgresql://postgres:@localhost/postgres
              LC_ALL: C.UTF-8
        - image: circleci/postgres:9.6
          environment:
              POSTGRES_USER: postgres
              POSTGRES_DB: postgres
              POSTGRES_PASSWORD: ''
    steps:
        - checkout
        - run:
            name: install-conda
            command: |
                wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O conda.sh
                bash conda.sh -b -p ~/miniconda
        - run:
            name: setup
            command: |
                ~/miniconda/bin/conda install --yes conda-build conda-verify anaconda-client postgresql
                ~/miniconda/bin/conda config --system --add channels conda-forge
                ~/miniconda/bin/psql -h localhost -U postgres -f db/nci.sql
                ~/miniconda/bin/psql -h localhost -U postgres -f db/tables.sql
        - run:
            name: build
            command: |
                # Enable coverage
                mv conda/run_test_coverage.sh conda/run_test.sh
                ~/miniconda/bin/conda build conda -c conda-forge --python=${PYTHON_VER}
        - run: 
            name: archive
            command: |
                mkdir /tmp/artefacts
                cp $(~/miniconda/bin/conda build conda --python=${PYTHON_VER} --output) /tmp/artefacts

        - persist_to_workspace:
            root: /tmp/artefacts
            paths: '*'

version: 2
jobs:
    py2:
        environment:
            PYTHON_VER: 2.7
        <<: *run_conda
    py3:
        environment:
            PYTHON_VER: 3
        <<: *run_conda

    publish:
        working_directory: /circleci
        docker:
            - image: scottwales/conda-build
        steps:
            - attach_workspace:
                at: /tmp/artefacts

            - run:
                anaconda --token "${ANACONDA_TOKEN}" upload --user "${ANACONDA_USER}" /tmp/artefacts/*.tar.bz2

workflows:
    version: 2
    build_and_publsh:
        jobs:
            - py2:
                filters:
                    tags:
                        only: /.*/

            - py3:
                filters:
                    tags:
                        only: /.*/

            - publish:
                requires:
                    - py2
                    - py3
                filters:
                    tags:
                        only: /.*/
                    branches:
                        ignore: /.*/
