name: arccssive2-dev

channels:
    - conda-forge
    - ScottWales
    - defaults

dependencies:
    - python
    - six
    - sqlalchemy
    - psycopg2
    - requests
    - click
    - pytest
    - keyring
    - git

    - pip:
        - docker-compose
