name: arccssive2-dev

channels:
    - conda-forge
    - defaults

dependencies:
    - python
    - six
    - sqlalchemy
    - psycopg2
    - requests
    - click
    - pytest

    - pip:
        - docker-compose
