package:
    name: clef
    version: {{ GIT_DESCRIBE_TAG }}

build:
    number: {{ GIT_DESCRIBE_NUMBER }}

source:
    git_url: ../

build:
    script: python setup.py install
    script_env:
        - LC_ALL # For click tests
        - CLEF_DB
    entry_points:
        - clef = clef.cli:clef

requirements:
    build:
        - python
        - pbr
    run:
        - python
        - six
        - sqlalchemy
        - psycopg2
        - requests
        - click
        - mock # [py27]

test:
    source_files:
        - setup.cfg
        - conftest.py
        - test
    requires:
        - pytest
    imports:
        - clef

about:
    home: https://github.com/coecms/clef
    license: Apache 2.0
    license_file: LICENSE-2.0.txt
    summary: clef
