package:
    name: arccssive2
    version: {{ GIT_DESCRIBE_TAG }}

build:
    number: {{ GIT_DESCRIBE_NUMBER }}
    string: {{ GIT_BUILD_STR }}

source:
    git_url: ../

build:
    script: python setup.py install
    script_env:
        - LC_ALL # For click tests
        - ARCCSSIVE_DB
    entry_points:
        - esgf = arccssive2.cli:esgf

requirements:
    build:
        - python
        - pbr
    run:
        - python
        - six
        - sqlalchemy
        - psycopg2
        - requests
        - click
        - keyring

test:
    source_files:
        - setup.cfg
        - conftest.py
        - test
    requires:
        - pytest
    commands:
        - py.test
    imports:
        - arccssive2

about:
    home: https://github.com/coecms/arccssive2
    license: Apache 2.0
    license_file: LICENSE-2.0.txt
    summary: arccssive2
